### ISSUE TITLE
Supporting windows?

### ISSUE THREAD

**Issue by catalin-florescu** [grandcentrix/AndroidCodeStyle#12]
I've just installed this plugin and i don't see any formatting. Does support windows?

**Comment by passsy** [comment]
We don't have a `.bat` to be executed on Windows. Have you executed the install script with `sh`?

```shell
> sh install.sh
```

Also, have you restarted Android Studio? It's the main reason the code style doesn't show up

**Comment by catalin-florescu** [comment]
Yes, i used shell to install it. Plugin was added into Code Styles, but there is no efect in code formatting using usual keys `Ctrl`+`Alt`+`L` (i restarted Android Studio after install). I tried using just `Ctrl`+`S`. Only one thing i noticed, it put a new empty line after new global variable, not one after another:

    int a;
    int b;
turns into

    int a;

    int b;

Also line length to 118

**Comment by passsy** [comment]
`Ctrl+Alt+L` (`Code -> Reformat Code`) only does formatting, not reordering. You have to manually run `Code -> Rearrange Code` or `Code -> Optimize Imports`.

Have you created a macro to combine all those?

**Comment by catalin-florescu** [comment]
How do i remove that space between variables?

**Comment by passsy** [comment]
Closing because we don't offer support for IntelliJ formatting tutorials and windows support is not the issue here
