### ISSUE TITLE
Rearrange code not workin in kotlin class

### ISSUE THREAD

**Issue by rulogarcillan** [grandcentrix/AndroidCodeStyle#30]
Rearrange code not workin in kotlin class.

Why?

Thanks

**Comment by StefMa** [comment]
Kotlin (or IntelliJ) doesn't provide a option for formating. I don't know
if it will come in the future or why it's not possible.

But state today (with everything <= AS 3.5) its not possible. Sry.

**Comment by rulogarcillan** [comment]
thanks
