### ISSUE TITLE
grandcentrix badly format XML views in android 3.5

### ISSUE THREAD

**Issue by rulogarcillan** [grandcentrix/AndroidCodeStyle#31]
Hi

grandcentrix  badly format XML views, move layouts and spoil the design

Thanks

**Comment by StefMa** [comment]
Thank you for the report. We noticed this as well and found a fix for it.
But currently not published here...

**Comment by rulogarcillan** [comment]
Thanks, will you publish the fix now that android 3.5 is official?

Thanks for your work
