### ISSUE TITLE
Moving code from xmls

### ISSUE THREAD

**Issue by SammyJankis** [grandcentrix/AndroidCodeStyle#35]
When I try to rearrange code in a xml, code style reorders the components of this xml. One example could be this one: 
Before rearrange :
<FrameLayout(main container)
<android.support.v7.widget.CardView
<LinearLayout

After rearrange : 
<FrameLayout(main container)
<LinearLayout
 <android.support.v7.widget.CardView
       
This changes the design of the xml...

**Comment by StefMa** [comment]
Thank you for reporting this issue.
This should be fixed by #32 (see also the original issue at #31).

I'm not aware from where do you came from. But you simply have to "update" the current codestyle from our master branch.

**Comment by SammyJankis** [comment]
Thanks for the info !!
