### ISSUE TITLE
Hungarian Notation

### ISSUE THREAD

**Issue by passsy** [grandcentrix/AndroidCodeStyle#4]
From the [AOSP Java Code Style for Contributors](https://source.android.com/source/code-style):
> ## Follow Field Naming Conventions
>
> - Non-public, non-static field names start with m.
> - Static field names start with s.
> - Other fields start with a lower case letter.
> - Public static final fields (constants) are ALL_CAPS_WITH_UNDERSCORES.
>
> For example:
```java
public class MyClass {
    public static final int SOME_CONSTANT = 42;
    public int publicField;
    private static MyClass sSingleton;
    int mPackagePrivate;
    private int mPrivate;
    protected int mProtected;
}
```
---

Our developer survey shows that we overall like the "identifier metadata" and will stick to this convention.
![screen shot 2017-08-22 at 21 42 34](https://user-images.githubusercontent.com/1096485/30855946-0768080e-a2b7-11e7-8806-e88fd20c2eca.png)

We don't believe that ["Today, our IDE’s can distinguish all these identifiers with colors so we don’t need any of this any more"](http://jakewharton.com/just-say-no-to-hungarian-notation/) because we often read code outside of IDEs when reviewing code.

Cédric Beust outlined his decision to introduce the `m`-prefix in his article ["I am the reason for Hungarian notation in Android"](http://beust.com/weblog/2017/07/17/i-am-the-reason-for-hungarian-notation-in-android/). Read this for further arguments for the `m`-prefix.

**Comment by passsy** [comment]
Kotlin has no fields (only backing fields) but [Properties](https://kotlinlang.org/docs/reference/properties.html). The m-Prefix doesn't make sense here. In worst case it would create getters such as `getMUser()` when calling it from Java.

**Don't use the m-Prefix in Kotlin**

**Comment by vincent-paing** [comment]
> From the AOSP Java Code Style for Contributors:

ASOP Java Code Style is for Android Open Source contributors, and should not be followed unless you're contributing to Android Open Source Project. I think it's better if the style follows the naming section of [Google Java Style](https://google.github.io/styleguide/javaguide.html#s5-naming)
